apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-run-data
  labels:
    project: headscale
    component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage