apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      project: monitoring
      component: prometheus
  template:
    metadata:
      labels:
        project: monitoring
        component: prometheus
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.2
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data