apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: headscale-config
    files:
      - ./conf/config.yaml

resources:
  - ./resources/config-pvc.yaml
  - ./resources/run-data-pvc.yaml

  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml