apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: bot

configMapGenerator:
  - name: discord-azure-boot-config
    files:
      - ./conf/config.json5

resources:
  - ./resources/deployment.yaml