apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
spec:
  volumes:
    - name: restore-volume
      persistentVolumeClaim:
        claimName: pvc-restore
  containers:
  - name: shell
    image: alpine
    command: [ "sh", "-c", "sleep infinity" ]
    volumeMounts:
      - mountPath: /mnt
        name: restore-volume