apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
spec:
  volumes:
    - name: restore-volume
      persistentVolumeClaim:
        claimName: restore-pvc
  containers:
  - name: shell
    image: alpine
    volumeMounts:
      - mountPath: /mnt
        name: restore-volume