apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: restore-volume-snapshot-content
spec:
  deletionPolicy: Delete
  driver: dobs.csi.digitalocean.com
  source:
    snapshotHandle: your-snapshot-ID
  volumeSnapshotRef:
    name: restore-volume-snapshot
    namespace: default