apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/emby-config-pvc.yaml
  - ./resources/media-pvc.yaml

  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml