apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/emby-config-pvc-do-block.yaml
  - ./resources/media-pv-do-block.yaml
  - ./resources/media-pvc-do-block.yaml
  - ./resources/encoding-cache-pvc-do-block.yaml

  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml