apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord-azure-boot

commonLabels:
  project: discord-azure-boot

resources:
  - ./namespace.yaml
  - ./bases/bot/
  - ./bases/mongo/