apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  overlay: brapcord
namePrefix: brapcord-
secretGenerator:
- name: chatgpt-discord-bot
  envs:
  - config.env
configMapGenerator:
- name: chatgpt-discord-bot
  literals:
  - REDIS_HOST=brapcord-redis
bases:
- ../../base