apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    project: discord-azure-boot
    component: mongo
spec:
  selector:
    project: discord-azure-boot
    component: mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: mongo