apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      project: discord-azure-boot
      component: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        project: discord-azure-boot
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0.7
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: dev-discord-azure-boot
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
