apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-csi-s3
  labels:
    project: media-server
    component: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3