apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  # Set ACME server
  - target:
      kind: ClusterIssuer
      name: issuer
    patch: |-
      - op: replace
        path: /spec/acme/server
        value: https://acme-v02.api.letsencrypt.org/directory
      - op: replace
        path: /metadata/name
        value: lets-encrypt-production-http01

  # Set ACME email
  - target:
      kind: ClusterIssuer
      name: issuer
    path: ./acme-email-patch.yaml

  # Rename secret
  - target:
      kind: ClusterIssuer
      name: issuer
    patch: |-
      - op: replace
        path: /spec/acme/privateKeySecretRef/name
        value: production-cert-manager-account-key
bases:
- ../bases/issuer