apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: prometheus
resources:
  - resources/stateful-set.yaml
  - resources/svc.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - conf/prometheus.yml
