apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

resources:
  - ./resources/cluster.yaml
  #- ./resources/rook-config-override.yaml
  - ./resources/ceph-block-pool.yaml
  - ./resources/storageclass.yaml
  - ./resources/ceph-toolbox.yaml