apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

resources:
  - ./resources/cluster.yaml

  - ./resources/ceph-block-pool.yaml
  - ./resources/block-storageclass.yaml

  - ./resources/cephfs-filesystem.yaml
  - ./resources/cephfs-storageclass.yaml

  - ./resources/ceph-toolbox.yaml