apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    project: chatgpt-discord-bot
    component: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1M
  storageClassName: do-block-storage