apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    email: user@example.com
    server: acme-example.com
    privateKeySecretRef:
      name: cert-manager-account-key
    solvers:
    - http01:
        ingress:
          class: nginx