apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    project: media-server
    component: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: sonarr
  template:
    metadata:
      labels:
        project: media-server
        component: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:3.0.10
          ports:
            - name: http
              containerPort: 8989
          
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: media
          persistentVolumeClaim:
            claimName: media-files