apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    project: media-server
    component: sonarr
spec:
  selector:
    project: media-server
    component: sonarr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http