apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frp-operator-manager-role
  labels:
    app.kubernetes.io/name: frp-operator
    app.kubernetes.io/instance: frp-operator
    app.kubernetes.io/managed-by: frp-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - clients/finalizers
  verbs:
  - update
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - clients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - upstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - upstreams/finalizers
  verbs:
  - update
- apiGroups:
  - frp.zufardhiyaulhaq.com
  resources:
  - upstreams/status
  verbs:
  - get
  - patch
  - update