apiVersion: v1
kind: ServiceAccount
metadata:
  name: frp-operator-controller-manager
  labels:
    app.kubernetes.io/name: frp-operator
    app.kubernetes.io/instance: frp-operator
    app.kubernetes.io/managed-by: frp-operator