apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay
  namespace: operators
spec:
  channel: stable-3.7
  name: project-quay
  source: operatorhubio-catalog
  sourceNamespace: olm