apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factorio
commonLabels:
  project: factorio
  component: server

configMapGenerator:
  - name: server-config
    envs:
      - conf/server-config.env

secretGenerator:
  - name: server-secret
    envs:
      - conf/server-secret.env
    files:
      - conf/server-rconpw.txt

resources:
  - resources/namespace.yaml
  - resources/statefulset.yaml
  - resources/service.yaml
