apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factorio
commonLabels:
  project: factorio
  component: server

configMapGenerator:
  - name: server-config
    envs:
      - conf/server.env

resources:
  - resources/namespace.yaml
  - resources/statefulset.yaml
  - resources/service.yaml
  - resources/ingress.yaml
