apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    project: monitoring
    component: alertmanager
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9093
