apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    project: media-server
    component: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: radarr
  template:
    metadata:
      labels:
        project: media-server
        component: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:version-4.6.4.7568
          ports:
            - name: http
              containerPort: 7878
          
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: media
          persistentVolumeClaim:
            claimName: media-files