apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    project: media-server
    component: radarr
spec:
  selector:
    project: media-server
    component: radarr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http