apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: youtube-dl-config
    files:
      - ./conf/config.json

resources:
  - ./resources/sqlite-pvc.yaml
  - ./resources/deployment.yaml
  - ./resources/service.yaml