apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl
  labels:
    project: media-server
    component: youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: youtube-dl
  template:
    metadata:
      labels:
        project: media-server
        component: youtube-dl
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: project
                    operator: In
                    values:
                      - media-server
                  - key: component
                    operator: In
                    values:
                      - emby
              topologyKey: kubernetes.io/hostname
      containers:
        - name: youtube-dl
          image: ergosteur/youtube-dl-webui:latest
          env:
            - name: CONF_FILE
              value: /opt/youtube-dl/conf/config.json
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: media-do-block
              mountPath: /media/
            - name: youtube-dl-config
              mountPath: /opt/youtube-dl/conf/
            - name: youtube-dl-sqlite
              mountPath: /opt/youtube-dl/data/
      volumes:
        - name: media-do-block
          persistentVolumeClaim:
            claimName: media-files-do-block
        - name: youtube-dl-sqlite
          persistentVolumeClaim:
            claimName: youtube-dl-sqlite
        - name: youtube-dl-config
          configMap:
            name: youtube-dl-config