apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-sqlite
  labels:
    project: media-server
    component: youtube-dl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage