apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: netbox
      component: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: netbox
        component: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:16-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data-do-block
              mountPath: /var/lib/postgresql/data/
              subPath: data
      volumes:
        - name: postgres-data-do-block
          persistentVolumeClaim:
            claimName: postgres-data-do-block

