apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: app-config
    files:
      - config.properties

secretGenerator:
  - name: app-secret
    literals:
      - username=admin
      - password=secret

commonLabels:
  app: open-exercise-warehouse

images:
  - name: my-app
    newTag: v1.0.0