apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
type: Opaque
stringData:
  MINIO_ROOT_USER: will be replaced
  MINIO_ROOT_PASSWORD: will be replaced

  MINIO_STORAGE_CLASS_STANDARD: "EC:2"
  MINIO_BROWSER: on