apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER=will be replaced
    export MINIO_ROOT_PASSWORD=will be replaced

    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER=on