apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotify
commonLabels:
  project: gotify
  component: gotify-server
resources:
- resources/namespace.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/ingress.yaml