apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify
  annotations:
    nginx.org/websocket-services: gotify
spec:
  ingressClassName: nginx
  rules:
  - host: "gotify.k8s.funkyboy.zone"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gotify
            port:
              number: 80