apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: gotify
  labels:
    project: gotify
    component: gotify-server
spec:
  selector:
    project: gotify
    component: gotify-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80