apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    project: media-server
    component: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      project: media-server
      component: prowlarr
  template:
    metadata:
      labels:
        project: media-server
        component: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:1.25.4
          ports:
            - name: http
              containerPort: 9696
          
          volumeMounts:
            - name: config-do-block
              mountPath: /config
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: config-do-block
          persistentVolumeClaim:
            claimName: prowlarr-config-do-block
