apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    project: media-server
    component: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: qbittorrent
  template:
    metadata:
      labels:
        project: media-server
        component: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:4.5.4
          ports:
            - name: qb-web-ui
              containerPort: 8080
              protocol: TCP
          env:
            - name: WEBUI_PORT
              value: "8080"
          volumeMounts:
            - name: qbittorrent-config-dir
              mountPath: /config/qBittorrent
            - name: media
              mountPath: /media
        - name: vpn
          image: qmcgaw/gluetun:v3.35.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: SERVER_REGIONS
              value: US New York
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-credentials
                  key: VPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-credentials
                  key: VPN_PASS
      volumes:
        - name: qbittorrent-config
          configMap:
            name: qbittorrent-config
        - name: qbittorrent-config-dir
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: media
          persistentVolumeClaim:
            claimName: media-files