apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    project: media-server
    component: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: qbittorrent
  template:
    metadata:
      labels:
        project: media-server
        component: qbittorrent
    spec:
      containers:
        - name: curl
          image: ubuntu:latest
          command:
            - sleep
            - infinity
        - name: vpn
          image: qmcgaw/gluetun:v3.35.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: SERVER_REGIONS
              value: US New York
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-credentials
                  key: VPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-credentials
                  key: VPN_PASS
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-files