apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-only-vpn
  labels:
    project: media-server
    component: qbittorrent
spec:
  podSelector:
    matchLabels:
      project: media-server
      component: qbittorrent
  policyTypes:
    - Egress