apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-access
  labels:
    project: media-server
    component: qbittorrent
spec:
  podSelector:
    matchLabels:
      project: media-server
      component: qbittorrent
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Requests from -arr services which use qBittorrent
    - from:
        - podSelector:
            matchLabels:
              project: media-server
              component: radarr
        - podSelector:
            matchLabels:
              project: media-server
              component: sonarr
      ports:
        - protocol: TCP
          port: 8080

    # Requests from Wireguard VPN
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wireguard
      ports:
        - protocol: TCP
          port: 8080
  
  egress:
    # Responses to -arr services which use qBittorrent
    - to:
        - podSelector:
            matchLabels:
              project: media-server
              component: radarr
        - podSelector:
            matchLabels:
              project: media-server
              component: sonarr
      ports:
        - protocol: TCP
          port: 8080

    # Responses to Wireguard VPN
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wireguard
      ports:
        - protocol: TCP
          port: 8080

    # VPN
    - to:
        - ipBlock:
            cidr: 191.96.227.97/32
        - ipBlock:
            cidr: 191.96.227.117/32
        - ipBlock:
            cidr: 191.96.227.124/32
        - ipBlock:
            cidr: 191.96.227.103/32
        - ipBlock:
            cidr: 191.96.227.127/32
        - ipBlock:
            cidr: 191.96.227.105/32
        - ipBlock:
            cidr: 191.96.227.119/32
        - ipBlock:
            cidr: 191.96.227.90/32

    - to:
        - ipBlock:
            cidr: 37.19.198.96/32
        - ipBlock:
            cidr: 37.19.198.95/32