apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-access
  labels:
    project: media-server
    component: qbittorrent
spec:
  podSelector:
    matchLabels:
      project: media-server
      component: qbittorrent
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Requests from -arr services which use qBittorrent
    - from:
        - podSelector:
            matchLabels:
              project: media-server
              component: radarr
        - podSelector:
            matchLabels:
              project: media-server
              component: sonarr
      ports:
        - protocol: TCP
          port: 8080

    # Requests from Wireguard VPN
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wireguard
      ports:
        - protocol: TCP
          port: 8080
  
  egress:
    # Responses to -arr services which use qBittorrent
    - to:
        - podSelector:
            matchLabels:
              project: media-server
              component: radarr
        - podSelector:
            matchLabels:
              project: media-server
              component: sonarr
      ports:
        - protocol: TCP
          port: 8080

    # Responses to Wireguard VPN
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wireguard
      ports:
        - protocol: TCP
          port: 8080

    # VPN
    # /32 CIDR covers one IP address
    - to:
      - ipBlock:
          cidr: 140.228.21.140/32
      - ipBlock:
          cidr: 140.228.21.145/32
      - ipBlock:
          cidr: 140.228.21.147/32
      - ipBlock:
          cidr: 140.228.21.156/32
      - ipBlock:
          cidr: 140.228.21.228/32
      - ipBlock:
          cidr: 140.228.21.229/32
      - ipBlock:
          cidr: 140.228.21.74/32
      - ipBlock:
          cidr: 140.228.21.77/32
      - ipBlock:
          cidr: 140.228.21.84/32
      - ipBlock:
          cidr: 140.228.21.88/32
      - ipBlock:
          cidr: 172.98.71.142/32
      - ipBlock:
          cidr: 172.98.71.159/32
