apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-internal-access
  labels:
    project: media-server
    component: qbittorrent
spec:
  podSelector:
    matchLabels:
      project: media-server
      component: qbittorrent
  policyTypes:
    - Egress
  egress:
    # Allow Kubernetes API
    # IP from: kubectl get endpoints
    - to:
        - ipBlock:
            cidr: 100.65.22.242/32
      ports:
        - protocol: TCP
          port: 443

    - to:
        - podSelector:
            matchLabels:
              project: media-server
              component: radarr
        - podSelector:
            matchLabels:
              project: media-server
              component: sonarr