apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  labels:
    project: media-server
    component: qbittorrent
data:
  qBittorrent.conf: |
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\DefaultSavePath=/downloads/
    Session\Port=6881
    Session\QueueingSystemEnabled=true
    Session\TempPath=/downloads/incomplete/
    Session\GlobalMaxRatio=0
    Session\DisableAutoTMMByDefault=false

    [LegalNotice]
    Accepted=true

    [Meta]
    MigrationVersion=4

    [Network]
    PortForwardingEnabled=false

    [Preferences]
    Connection\PortRangeMin=6881
    Connection\UPnP=false
    Downloads\SavePath=/downloads/
    Downloads\TempPath=/downloads/incomplete/
    WebUI\Address=*
    WebUI\Port=8080
    WebUI\ServerDomains=*

    # Required to allow access from ports besides 8080
    WebUI\HostHeaderValidation=false

    WebUI\Username=admin

  categories.json: |
    {
        "radarr": {
            "save_path": "/downloads/movies"
        },
        "tv-sonarr": {
            "save_path": "/downloads/tv"
        }
    }