apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noahhuppert-com
spec:
  project: default
  source:
    repoURL: https://github.com/Noah-Huppert/NoahHuppert.com.git
    targetRevision: HEAD
    path: ./kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: noahhuppert-com
