apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-discord-bot
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: chatgpt-discord-bot
        image: noahhuppert/chatgpt-discord-bot:v1.0.0-alpha7
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatgpt-discord-bot
              key: OPENAI_API_KEY
        - name: DISCORD_GUILD_ID
          valueFrom:
            secretKeyRef:
              name: chatgpt-discord-bot
              key: DISCORD_GUILD_ID
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: chatgpt-discord-bot
              key: DISCORD_BOT_TOKEN
        - name: DISCORD_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: chatgpt-discord-bot
              key: DISCORD_CHANNEL_ID
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: chatgpt-discord-bot
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"