components:
  - path: ./
    strategy: diff
  - path: ./base/wireguard/
    strategy: diff
  - path: ./base/media-server/
    strategy: diff
  - path: ./base/monitoring/overlays/operators/
    strategy: big-diff