components:
  # Base Cluster Functionality
  - path: ./base/priority-classes
  - path: ./base/nginx-ingress
  - path: ./base/operator-lifecycle-manager
  - path: ./base/cert-manager

  # Cluster Adminstrative Tools
  - path: ./base/kubernetes-dashboard
  - path: ./base/wireguard/
  - path: ./base/coredns/
  # - path: ./base/monitoring/resources/kube-prometheus/crds
  #   strategy: big-diff
  # - path: ./base/monitoring/resources/kube-prometheus/core/
  - path: ./base/iperf/

  # End User Services
  - path: ./base/media-server/
  - path: ./base/kimai/
  - path: ./base/actual-budget/
  - path: ./base/discord-azure-boot/
  - path: ./base/noahhuppert-com/
  - path: ./base/netbox/
  - path: ./base/gotify/production
