components:
  - path: ./
  - path: ./base/wireguard/
  - path: ./base/media-server/
  - path: ./base/kimai/
  - path: ./base/actual-budget/
  - path: ./base/coredns/
  - path: ./base/discord-azure-boot/
  - path: ./base/noahhuppert-com/

  # See base/monitoring/resources/README.md#deployment
  - path: ./base/monitoring/resources/kube-prometheus/crds
    strategy: big-diff
  - path: ./base/monitoring/resources/kube-prometheus/core/
  - path: ./base/netbox/