apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # Base
  - ./base/kubernetes-dashboard
  - ./base/operator-lifecycle-manager
  - ./base/argocd
  - ./base/tektoncd
  - ./base/quay

  # Services
  - ./base/gotify/deploy