apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # Base
  - ./base/nginx-ingress
  - ./base/kubernetes-dashboard
  - ./base/monitoring/overlays/production

  # Operators
  - ./base/operator-lifecycle-manager
  #- ./base/argocd
  #- ./base/tektoncd
  - ./base/rook
  - ./base/quay
  - ./base/cert-manager
  #- ./base/minio

  # Services
  - ./base/gotify/production
  - ./base/chatgpt-discord-bot/deploy
  - ./base/media-server/production
  - ./base/headscale