apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale

resources:
  - ./resources/namespace.yaml

  - ./resources/config-map.yaml
  - ./resources/config-pvc.yaml
  - ./resources/run-data-pvc.yaml

  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/ingress.yaml