apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: Secret
      name: pia-vpn-credentials
    path: ./pia-vpn-secret-patch.yaml

resources:
  - ./resources/pia-vpn-secret.yaml
  - ./resources/pia-openvpn-config.yaml

  - ./resources/qbittorrent-config-secret.yaml
  
  - ./resources/deployment.yaml
  - ./resources/service.yaml