apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: Secret
      name: pia-vpn-credentials
    path: ./patches/pia-vpn-secret-patch.yaml

secretGenerator:
  - name: qbittorrent-port-updater
    envs:
      - ./conf/qbittorrent-port-updater.env

resources:
  - ./resources/pia-vpn-secret.yaml
  - ./resources/qbittorrent-config-pvc-do-block.yaml
  
  - ./resources/deployment.yaml
  - ./resources/network-policy.yaml
  - ./resources/qbittorrent-service.yaml
  - ./resources/gluten-service.yaml