apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge
  labels:
    project: protonmail-bridge
    component: bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage