apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

configMapGenerator:
  - name: coredns-custom
    files:
      - conf/infoline.server
      - conf/infoline.db

  - name: coredns
    files:
      - conf/Corefile

generatorOptions:
  disableNameSuffixHash: true
