apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-redis
spec:
  selector:
    matchLabels:
      app: netbox
      component: data-redis
  serviceName: data-redis
  template:
    metadata:
      labels:
        app: netbox
        component: data-redis
    spec:
      containers:
        - name: redis
          image: docker.io/redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-redis
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: data-redis-data-do-block
              mountPath: /data
      volumes:
        - name: data-redis-data-do-block
          persistentVolumeClaim:
            claimName: data-redis-data-do-block

