apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-csi-s3
  labels:
    project: media-server
    component: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3