apiVersion: v1
kind: Service
metadata:
  name: youtube-dl
  labels:
    project: media-server
    component: youtube-dl
spec:
  selector:
    project: media-server
    component: youtube-dl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http