apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  type: LoadBalancer
  selector:
    project: factorio
    component: server
  ports:
    - name: game # out
      targetPort: game # in
      port: 34197 # out
      protocol: UDP # out
    - name: rcon
      targetPort: rcon
      port: 27015
      protocol: TCP
