apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      project: factorio
      component: server
  serviceName: factorio
  template:
    metadata:
      labels:
        project: factorio
        component: server
    spec:
      securityContext:
        runAsUser: 845
        runAsGroup: 845
        fsGroup: 845
      initContainers:
        # Move configmap and secret files into a tmp volume bc the factorio container's entrypoint will write new files next to ours
        # This normally isn't possible bc if you mount a file from a configmap or secret it makes the whole dir readonly
        - name: copy-config
          image: alpine:latest
          command: [ "/bin/sh", "-c" ]
          args: [ "cp /mnt/factorio-config/* /factorio/config" ]
          volumeMounts:
            - name: factorio-config-overlay
              mountPath: /factorio/config
            - name: factorio-secret
              mountPath: /mnt/factorio-config/rconpw
              subPath: rconpw
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.15
          ports:
            - name: game
              containerPort: 34197
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
          env:
            - name: PORT
              value: "34197"
            - name: RCON_PORT
              value: "27015"
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: USERNAME
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: TOKEN
          volumeMounts:
            - name: factorio-config-overlay
              mountPath: /factorio/config
            - name: factorio-saves
              mountPath: /factorio/saves/
      volumes:
        - name: factorio-secret
          secret:
            secretName: server-secret
            items:
              - key: server-rconpw.txt
                path: rconpw
        - name: factorio-config-overlay
          emptyDir: {}
          
  volumeClaimTemplates:
    - metadata:
        name: factorio-saves
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 2Gi
