apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      project: factorio
      component: server
  serviceName: factorio
  template:
    metadata:
      labels:
        project: factorio
        component: server
    spec:
      # securityContext:
      #   runAsUser: 845
      #   runAsGroup: 845
      #   fsGroup: 845
      # initContainers:
      #   - name: chown
      #     image: alpine:latest
      #     securityContext:
      #       runAsUser: 0 #845
      #       runAsGroup: 0 #845
      #     command:
      #       - /bin/sh
      #       - -c
      #     args:
      #       - "mkdir -p /factorio/{saves,config} && chown -R 845:845 /factorio/"
      #     volumeMounts:
      #       - name: factorio-saves
      #         mountPath: /factorio/saves/
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.10
          command: ["/bin/bash"]
          args: ["-c", "echo $(id -u) && sleep infinity"]
          # securityContext:
          #   runAsUser: 845
          #   runAsGroup: 845
          #   # cfsGroup: 845
          ports:
            - name: game
              containerPort: 34197
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
          env:
            - name: PORT
              value: "34197"
            - name: RCON_PORT
              value: "27015"
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: USERNAME
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: TOKEN
          volumeMounts:
            - name: factorio-saves
              mountPath: /factorio/saves/
            - name: factorio-secret
              mountPath: /factorio/config/rconpw
              subPath: rconpw
      volumes:
        - name: factorio-secret
          secret:
            secretName: server-secret
            items:
              - key: server-rconpw.txt
                path: rconpw
          
  volumeClaimTemplates:
    - metadata:
        name: factorio-saves
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 2Gi
