apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-server-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1M
  storageClassName: do-block-storage