apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files
  labels:
    project: media-server
    component: files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: cephfs-media-server