apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-csi-s3
  labels:
    project: media-server
    component: emby
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3
