apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files-csi-s3
  labels:
    project: media-server
    component: files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: csi-s3