apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale

resources:
  - ./resources/namespace.yaml

commonLabels:
  project: headscale
  
bases:
  - ../bases/control-server/
  - ../bases/web-ui/