apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus
  replicas: 3
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      project: monitoring
      component: prometheus
  template:
    metadata:
      labels:
        project: monitoring
        component: prometheus
    spec:
      securityContext:
        fsGroup: 8000
      containers:
      - name: prometheus
        image: prom/prometheus:v2.54.1
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: prometheus-replica-data
          mountPath: /prometheus
        - name: config
          mountPath: /etc/prometheus/
        livenessProbe:
          httpGet:
            path: /api/v1/status/config
            port: http
      volumes:
      - name: config
        configMap:
          name: prometheus-config
          items:
            - key: prometheus.yml
              path: prometheus.yml
  volumeClaimTemplates:
    - metadata:
        name: prometheus-replica-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
