apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    project: monitoring
    component: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
