apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-server

commonLabels:
  project: media-server

resources:
  - ./namespace.yaml

  - bases/emby
  - bases/qbittorrent
  - bases/jellyseerr
  - bases/radarr
  - bases/sonarr
  - bases/prowlarr
  - bases/jellyfin
