apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: netbox
  component: postgres

resources:
  - resources/service.yaml

  - resources/pvc-do-block.yaml
  - resources/stateful-set.yaml

secretGenerator:
  - name: postgres
    envs:
      - conf/postgres.env