apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    project: media-server
    component: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: prowlarr
  template:
    metadata:
      labels:
        project: media-server
        component: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:1.7.4
          ports:
            - name: http
              containerPort: 9696
          
          volumeMounts:
            - name: config-csi-s3
              mountPath: /config
      volumes:
        - name: config-csi-s3
          persistentVolumeClaim:
            claimName: prowlarr-config-csi-s3