apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    project: media-server
    component: prowlarr
spec:
  selector:
    project: media-server
    component: prowlarr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http