apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iperf
resources:
  - ./resources/namespace.yaml
  - ./resources/ingress.yaml
  - ./resources/service.yaml
  - ./resources/deployment.yaml

commonLabels:
  project: iperf
