apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      project: media-server
      component: wireguard-sidecar
  template:
    metadata:
      labels:
        project: media-server
        component: wireguard-sidecar
    spec:
      serviceAccountName: wireguard-sidecar
      containers:
      - name: wireguard-sidecar
        image: noahhuppert/wireguard-sidecar:latest
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
        env:
          - name: WIREGUARD_PEER
            value: media-server-sidecar