apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wireguard

resources:
  - ./resources/namespace.yaml
  - ./resources/server.yaml
  
  - ./resources/pascal-peer.yaml
  - ./resources/noah-s23-peer.yaml